### ISSUE TITLE
Installed the app, but the issue persists – no noticeable difference

### ISSUE THREAD

**Issue by edardev** [Ponnusamy1-V/frappe-pdf#8]
Hello,

I installed the frappe-pdf app, but I am still encountering issues when attempting to generate PDFs and sending emails with attached Invoices for example

**Installed Apps**
- ERPNext: v15.40.0
- Frappe Framework: v15.46.0
- Frappe Pdf: v0.0.1 (main)

![image](https://github.com/user-attachments/assets/173608fd-69b6-4f05-9176-3d5097a860ee)

`
### App Versions
```
{
	"erpnext": "15.40.0",
	"frappe": "15.46.0",
	"frappe_pdf": "0.0.1"
}
```
### Route
```
Form/Email Queue/qorjhp77aj
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 114, in application
    response = frappe.api.handle(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
           ^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
           ^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/__init__.py", line 1781, in call
    return fn(*args, **newargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/email/doctype/email_queue/email_queue.py", line 447, in send_now
    record.send()
  File "apps/frappe/frappe/email/doctype/email_queue/email_queue.py", line 167, in send
    message = ctx.build_message(recipient.recipient)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/email/doctype/email_queue/email_queue.py", line 315, in build_message
    message = self.include_attachments(message)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/email/doctype/email_queue/email_queue.py", line 392, in include_attachments
    print_format_file = frappe.attach_print(**attachment)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/__init__.py", line 2238, in attach_print
    else get_print(doctype, name, **kwargs)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/__init__.py", line 2197, in get_print
    return get_pdf(html, options=pdf_options, output=output) if as_pdf else html
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe_pdf/frappe_pdf/__init__.py", line 13, in pdf
    return get_pdf(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/utils/pdf.py", line 90, in get_pdf
    filedata = pdfkit.from_string(html, options=options or {}, verbose=True)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "env/lib/python3.11/site-packages/pdfkit/api.py", line 75, in from_string
    return r.to_pdf(output_path)
           ^^^^^^^^^^^^^^^^^^^^^
  File "env/lib/python3.11/site-packages/pdfkit/pdfkit.py", line 201, in to_pdf
    self.handle_error(exit_code, stderr)
  File "env/lib/python3.11/site-packages/pdfkit/pdfkit.py", line 155, in handle_error
    raise IOError('wkhtmltopdf reported an error:\n' + stderr)
OSError: wkhtmltopdf reported an error:
Exit with code 1 due to network error: ConnectionRefusedError


```
### Request Data
```
{
	"type": "POST",
	"args": {
		"name": "qorjhp77aj"
	},
	"btn": {
		"0": {
			"jQuery3700186370230675375841": {
				"events": {
					"click": [
						{
							"type": "click",
							"origType": "click",
							"guid": 3570,
							"namespace": ""
						}
					]
				}
			}
		},
		"length": 1
	},
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.email.doctype.email_queue.email_queue.send_now",
	"request_id": null
}
```
### Response Data
```
{
	"exception": "",
	"exc_type": "OSError",
	"_exc_source": "frappe_pdf (app)"
}
```
`

```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 114, in application
    response = frappe.api.handle(request)
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1781, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/utils/print_format.py", line 234, in download_pdf
    pdf_file = frappe.get_print(
  File "apps/frappe/frappe/__init__.py", line 2197, in get_print
    return get_pdf(html, options=pdf_options, output=output) if as_pdf else html
  File "apps/frappe_pdf/frappe_pdf/__init__.py", line 13, in pdf
    return get_pdf(*args, **kwargs)
  File "apps/frappe/frappe/utils/pdf.py", line 90, in get_pdf
    filedata = pdfkit.from_string(html, options=options or {}, verbose=True)
  File "env/lib/python3.11/site-packages/pdfkit/api.py", line 75, in from_string
    return r.to_pdf(output_path)
  File "env/lib/python3.11/site-packages/pdfkit/pdfkit.py", line 201, in to_pdf
    self.handle_error(exit_code, stderr)
  File "env/lib/python3.11/site-packages/pdfkit/pdfkit.py", line 155, in handle_error
    raise IOError('wkhtmltopdf reported an error:\n' + stderr)
OSError: wkhtmltopdf reported an error:
Exit with code 1 due to network error: ConnectionRefusedError
```

**Comment by Ponnusamy1-V** [comment]
Hello @edardev , the issue you mentioned here is related to wkhtmltopdf, you can try reinstall the wkhtmltopdf.

Or, go to print settings page and then enable the option `Generate PDF using Google Chrome`. Make sure `google-chrome` is installed in your server.

Also mention your installation method like AWS or frappecloud or else

**Comment by auliabismar** [comment]
hi, I am using fappe 15.63.1, but didn't see this option in print settings.
Is there any step that I have to do before turn on this option?

**Comment by Ponnusamy1-V** [comment]
@auliabismar, for version-15, you can use [print desginer](https://github.com/frappe/print_designer)
